---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 'service-mesh-demo-api'
    version: v1
  name: api
  namespace: '{{ .Values.project.name }}'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 'service-mesh-demo-api'
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: 'service-mesh-demo-api'
        version: v1
    spec:
      containers:
        - image: 'image-registry.openshift-image-registry.svc:5000/demo/api:latest'
          name: api
          ports:
            - containerPort: 8080
