---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: 'service-mesh-demo-api'
    version: v1
  name: api
  namespace: '{{ .Values.project.name }}'
spec:
  ports:
    - name: quarkus-default
      port: 8080
      targetPort: 8080
  selector:
    app: 'service-mesh-demo-api'
    version: v1
