{{- range .Values.databases }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: '{{ .name }}'
    app.kubernetes.io/part-of: service-mesh-demo
  name: '{{ .name }}'
  namespace: '{{ .Values.project.name }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/component: '{{ .name }}'
      app.kubernetes.io/part-of: service-mesh-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/component: '{{ .name }}'
        app.kubernetes.io/part-of: service-mesh-demo
    spec:
      containers:
        - env:
            - name: POSTGRESQL_USER
              value: '{{ .username }}'
            - name: POSTGRESQL_PASSWORD
              value: '{{ .password }}'
            - name: POSTGRESQL_DATABASE
              value: '{{ .name }}'
          image: 'registry.redhat.io/rhel9/postgresql-13:latest'
          name: database
{{- end }}
