{{- range .Values.databases }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 'service-mesh-demo-{{ .name }}'
    version: v1
  name: '{{ .name }}'
  namespace: '{{ $.Values.project.name }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'service-mesh-demo-{{ .name }}'
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: 'service-mesh-demo-{{ .name }}'
        version: v1
    spec:
      containers:
        - env:
            - name: POSTGRESQL_USER
              value: '{{ .username }}'
            - name: POSTGRESQL_PASSWORD
              value: '{{ .password }}'
            - name: POSTGRESQL_DATABASE
              value: '{{ .name }}'
          image: 'registry.redhat.io/rhel9/postgresql-13:latest'
          name: database
{{- end }}
