{{- range .Values.databases }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: 'service-mesh-demo-{{ .name }}'
    version: v1
  name: '{{ .name }}'
  namespace: '{{ $.Values.project.name }}'
spec:
  ports:
    - name: tcp
      port: 5432
      targetPort: 5432
  selector:
    app: 'service-mesh-demo-{{ .name }}'
    version: v1
{{- end }}
