{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: quarkus
    app.kubernetes.io/component: '{{ .name }}'
    app.kubernetes.io/part-of: service-mesh-demo
  name: '{{ .name }}'
  namespace: '{{ $.Values.project.name }}'
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus
      app.kubernetes.io/component: '{{ .name }}'
      app.kubernetes.io/part-of: service-mesh-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: quarkus
        app.kubernetes.io/component: '{{ .name }}'
        app.kubernetes.io/part-of: service-mesh-demo
    spec:
      containers:
        - image: 'image-registry.openshift-image-registry.svc:5000/demo/service1:latest'
          name: service
{{- end }}
