{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 'service-mesh-demo-{{ .name }}'
    version: v1
  name: '{{ .name }}'
  namespace: '{{ $.Values.project.name }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'service-mesh-demo-{{ .name }}'
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        app: 'service-mesh-demo-{{ .name }}'
        version: v1
    spec:
      containers:
        - image: 'image-registry.openshift-image-registry.svc:5000/demo/{{ .name }}:latest'
          name: service
          ports:
            - containerPort: 8080
{{- end }}
