{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: 'service-mesh-demo-{{ .name }}'
    version: v1
  name: '{{ .name }}'
  namespace: '{{ $.Values.project.name }}'
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: 'service-mesh-demo-{{ .name }}'
    version: v1
{{- end }}
