---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: '{{ .Values.project.name }}'
spec:
  ports:
    - name: postgres-default
      port: 5432
      targetPort: 5432
  selector:
    matchLabels:
      app.kubernetes.io/name: service-mesh-demo
      app.kubernetes.io/component: database-instance
