quarkus:
  package:
    type: uber-jar
  rest-client:
    service1:
      scope: 'javax.inject.Singleton'
      url: 'http://service1.demo.svc:8080/accounts'
    service2:
      scope: 'javax.inject.Singleton'
      url: 'http://service2.demo.svc:8080/agencies'
