INSERT INTO AGENCIES (AGENCY_ID, CITY, VERSION) VALUES ('A001', 'Roma', 0);
INSERT INTO AGENCIES (AGENCY_ID, CITY, VERSION) VALUES ('A002', 'Milano', 0);
INSERT INTO AGENCIES (AGENCY_ID, CITY, VERSION) VALUES ('A003', 'Napoli', 0);
