---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/charts/databases
    repoURL: 'https://github.com/agbaroni/service-mesh-demo.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: gitops/charts/services
    repoURL: 'https://github.com/agbaroni/service-mesh-demo.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
